devices([
   "iPhone 11 Pro Max",  # 6.5"
  # "iPhone 11 Pro",      # 5.8"
  "iPhone 8 Plus",      # 5.5"
  # "iPhone 8",           # 4.7
])

languages([
   "en-US",
   "de-DE",
])

# The name of the scheme which contains the UI Tests
scheme("UITests")

# Activate dark mode
# dark_mode(true)


stop_after_first_error(true)
number_of_retries(2)

# erase_simulator(true)
#clean(true)


# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["SKIP_ANIMATIONS"])
# if ProcessInfo().arguments.contains("SKIP_ANIMATIONS") {
#    UIView.setAnimationsEnabled(false)
# }

localize_simulator(true)
# erase_simulator(true)
# For more information about all available options run
# fastlane action snapshot

concurrent_simulators(false)
